apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: 
    - "--no-push"
    volumeMounts:
      - name: app-files
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: app-files
      hostPath:
        path: /home/ec2-user/connected-app
        type: Directory